#pragma once

#define PCI_MAX_CLASS                               21

#define PCI_SUBCLASS_OTHER                              0x80

#define PCI_CLASS_UNCLASSIFIED                      0x00
#define PCI_SUBCLASS_UNCLASS_NON_VGA_COMPATIBLE         0x00
#define PCI_SUBCLASS_UNCLASS_VGA_COMPATIBLE             0x01

#define PCI_CLASS_MASS_STORAGE_CONTROLLER           0x01
#define PCI_SUBCLASS_STRG_SCSI_BUS_CONTROLLER           0x00
#define PCI_SUBCLASS_STRG_IDE_CONTROLLER                0x01
#define PCI_SUBCLASS_STRG_FLOPPY_DISK_CONTROLLER        0x02
#define PCI_SUBCLASS_STRG_IPI_BUS_CONTROLLER            0x03
#define PCI_SUBCLASS_STRG_RAID_CONTROLLER               0x04
#define PCI_SUBCLASS_STRG_ATA_CONTROLLER                0x05
#define PCI_SUBCLASS_STRG_SERIAL_ATA_CONTROLLER         0x06
#define PCI_SUBCLASS_STRG_SERIAL_ATTCH_SCSI_CONTROLLER  0x07
#define PCI_SUBCLASS_STRG_NON_VOLATILE_MEM_CONTROLLER   0x08

#define PCI_CLASS_NETWORK_CONTROLLER                0x02
#define PCI_SUBCLASS_NET_ETHERNET_CONTROLLER            0x00
#define PCI_SUBCLASS_NET_TOKEN_RING_CONTROLLER          0x01
#define PCI_SUBCLASS_NET_FDDI_CONTROLLER                0x02
#define PCI_SUBCLASS_NET_ATM_CONTROLLER                 0x03
#define PCI_SUBCLASS_NET_ISDN_CONTROLLER                0x04
#define PCI_SUBCLASS_NET_WORLDFIP_CONTROLLER            0x05
#define PCI_SUBCLASS_NET_PICMG__MULTI_COMP_CONTROLLER   0x06
#define PCI_SUBCLASS_NET_INFINIBAND_CONTROLLER          0x07
#define PCI_SUBCLASS_NET_FABRIC_CONTROLLER              0x08

#define PCI_CLASS_DISPLAY_CONTROLLER                0x03
#define PCI_SUBCLASS_DPLY_VGA_COMPATIBLE_CONTROLLER     0x00
#define PCI_SUBCLASS_DPLY_XGA_CONTROLLER                0x01
#define PCI_SUBCLASS_DPLY_3D_CONTROLLER                 0x02

#define PCI_CLASS_MULTIMEDIA_CONTROLLER             0x04
#define PCI_SUBCLASS_MEDIA_VIDEO_CONTROLLER             0x00
#define PCI_SUBCLASS_MEDIA_AUDIO_CONTROLLER             0x01
#define PCI_SUBCLASS_MEDIA_COMPUTER_TELEPHONY_DEVICE    0x02
#define PCI_SUBCLASS_MEDIA_AUDIO_DEVICE                 0x03

#define PCI_CLASS_MEMORY_CONTROLLER                 0x05
#define PCI_SUBCLASS_MEM_RAM_CONTROLLER                 0x00
#define PCI_SUBCLASS_MEM_FLASH_CONTROLLER               0x01

#define PCI_CLASS_BRIDGE                            0x06
#define PCI_SUBCLASS_HOST_BRIDGE                        0x00
#define PCI_SUBCLASS_ISA_BRIDGE                         0x01
#define PCI_SUBCLASS_EISA_BRIDGE                        0x02
#define PCI_SUBCLASS_MCA_BRIDGE                         0x03
#define PCI_SUBCLASS_PCI_TO_PCI_BRIDGE                  0x04
#define PCI_SUBCLASS_PCMCIA_BRIDGE                      0x05
#define PCI_SUBCLASS_NUBUS_BRIDGE                       0x06
#define PCI_SUBCLASS_CARDBUS_BRIDGE                     0x07
#define PCI_SUBCLASS_RACEWAY_BRIDGE                     0x08
#define PCI_SUBCLASS_PCI_TO_PCI_BRIDGE_2                0x09
#define PCI_SUBCLASS_INFINIBAND_TO_PCI_BRIDGE           0x0a

#define PCI_CLASS_SIMPLE_COMMUNICATION_CONTROLLER   0x07
#define PCI_SUBCLASS_SCC_SERIAL_CONTROLLER              0x00
#define PCI_SUBCLASS_SCC_PARALLEL_CONTROLLER            0x01
#define PCI_SUBCLASS_SCC_MULTIPORT_SERIAL_CONTROLLER    0x02
#define PCI_SUBCLASS_SCC_MODEM                          0x03
#define PCI_SUBCLASS_SCC_IEEE_488_GPIB_CONTROLLER       0x04
#define PCI_SUBCLASS_SCC_SMART_CARD_CONTROLLER          0x05

#define PCI_CLASS_BASE_SYSTEM_PERIPHERAL            0x08
#define PCI_SUBCLASS_BASE_PIC                           0x00
#define PCI_SUBCLASS_BASE_DMA_CONTROLLER                0x01
#define PCI_SUBCLASS_BASE_TIMER                         0x02
#define PCI_SUBCLASS_BASE_RTC_CONTROLLER                0x03
#define PCI_SUBCLASS_BASE_PCI_GOT_PLUG_CONTROLLER       0x04
#define PCI_SUBCLASS_BASE_SD_HOST_CONTROLLER            0x05
#define PCI_SUBCLASS_BASE_IOMMU                         0x06

#define PCI_CLASS_INPUT_DEVICE_CONTROLLER           0x09
#define PCI_SUBCLASS_INPUT_KEYBOARD_CONTROLLER          0x00
#define PCI_SUBCLASS_INPUT_DIGITIZER_PEN                0x01
#define PCI_SUBCLASS_INPUT_MOUSE_CONTROLLER             0x02
#define PCI_SUBCLASS_INPUT_SCANNER_CONTROLLER           0x03
#define PCI_SUBCLASS_INPUT_GAMEPORT_CONTROLLER          0x04

#define PCI_CLASS_DOCKING_STATION                   0x0a
#define PCI_SUBCLASS_GENERIC                            0x00

#define PCI_CLASS_PROCESSOR                         0x0b
#define PCI_SUBCLASS_PROCESSOR_386                      0x00
#define PCI_SUBCLASS_PROCESSOR_486                      0x01
#define PCI_SUBCLASS_PROCESSOR_PENTIUM                  0x02
#define PCI_SUBCLASS_PROCESSOR_PENTIUM_PRO              0x03
#define PCI_SUBCLASS_PROCESSOR_ALPHA                    0x04
#define PCI_SUBCLASS_PROCESSOR_POWER_PC                 0x05
#define PCI_SUBCLASS_PROCESSOR_MIPS                     0x06
#define PCI_SUBCLASS_PROCESSOR_CO_PROCESSOR             0x07

#define PCI_CLASS_SERIAL_BUS_CONTROLLER             0x0c
#define PCI_SUBCLASS_SERIAL_FIREWIRE_CONTROLLER         0x00
#define PCI_SUBCLASS_SERIAL_ACCESS_BUS_CONTROLLER       0x01
#define PCI_SUBCLASS_SERIAL_SSA                         0x02
#define PCI_SUBCLASS_SERIAL_USB_CONTROLLER              0x03
#define PCI_SUBCLASS_SERIAL_FIBRE_CHANNEL               0x04
#define PCI_SUBCLASS_SERIAL_SMBUS_CONTROLLER            0x05
#define PCI_SUBCLASS_SERIAL_INFINIBAND_CONTROLLER       0x06
#define PCI_SUBCLASS_SERIAL_IPMI_INTERFACE              0x07
#define PCI_SUBCLASS_SERIAL_SERCOS_INTERFACE            0x08
#define PCI_SUBCLASS_CANBUS_CONTROLLER                  0x09

#define PCI_CLASS_WIRELESS_CONTROLLER               0x0d
#define PCI_SUBCLASS_WLESS_IRDA_COMP_CONTROLLER         0x00
#define PCI_SUBCLASS_WLESS_CONSUMER_IR_CONTROLLER       0x01
#define PCI_SUBCLASS_WLESS_RF_CONTROLLER                0x10
#define PCI_SUBCLASS_WLESS_BLUETOOTH_CONTROLLER         0x11
#define PCI_SUBCLASS_WLESS_BORADBAND_CONTROLLER         0x12
#define PCI_SUBCLASS_WLESS_ETHERNET_CONTROLLER_802_1a   0x20
#define PCI_SUBCLASS_WLESS_ETHERNET_CONTROLLER_802_1b   0x21

#define PCI_CLASS_INTELLIGENT_CONTROLLER            0x0e
#define PCI_SUBCLASS_I2O                                0x00

#define PCI_CLASS_SATELLITE_COMUNICATION_CONTROLLER 0x0f
#define PCI_SUBCLASS_SATELLITE_TV_CONTROLLER            0x00
#define PCI_SUBCLASS_SATELLITE_AUDIO_CONTROLLER         0x01
#define PCI_SUBCLASS_SATELLITE_VOICE_CONTROLLER         0x02
#define PCI_SUBCLASS_SATELLITE_DATA_CONTROLLER          0x03

#define PCI_CLASS_ENCRYPTION_CONTROLLER             0x10
#define PCI_SUBCLASS_NETWORK_AND_COMPUTEING_EN_DE       0x00
#define PCI_SUBCLASS_ENERTAINEMENT_EN_DE                0x10

#define PCI_CLASS_SIGNAL_PROCESSING_CONTROLLER      0x11
#define PCI_SUBCLASS_SIGNAL_DPIO_MODULE                 0x00
#define PCI_SUBCLASS_SIGNAL_PERFORMANCE_COUNTER         0x01
#define PCI_SUBCLASS_SIGNAL_COMMUNICATION_SYNC          0x10
#define PCI_SUBCLASS_SIGNAL_PROCESSING_MANAGEMENT       0x20

#define PCI_CLASS_PROCESSING_ACCELERATOR            0x12

#define PCI_CLASS_NON_ESSENTIAL_INSTRUMENTATION     0x13

#define PCI_CLASS_CO_PROCESSOR                      0x40